blank_issues_enabled: false
contact_links:
  - name: ðŸš¨ Security Vulnerability Report
    url: https://github.com/emlog/emlog/blob/master/SECURITY.md
    about: Found a security issue? Please submit it according to this guide, do not post it publicly in Issues!